date: 2026-08-29
time: 12:00
venue:
  en: Grace Chinese Lutheran Church
  zh_tw: 西雅圖恩惠堂
  zh_cn: 西雅图恩惠堂
address:
  en: 538 NE 127th St  Seattle, WA 98125
  zh_tw: 538 NE 127th St  Seattle, WA 98125
  zh_cn: 538 NE 127th St  Seattle, WA 98125
mapsUrl: https://maps.app.goo.gl/DDnzLbKD9RSqvLiNA
livestreamUrl: ""
